version: 1
project:
  # open_access: true
  license:
    content: CC-BY-4.0
  abbreviations:
    PURE: protein synthesis using recombinant elements
site:
  template: book-theme
  nav: 
    - title: Documentation
      url: https://docs.nucleus.engineering/
    - title: Hub
      url: https://beta-hub.nucleus.engineering/hub/login?next=%2Fhub%2F
    - title: Developer Notes
      url: https://devnotes.nucleus.engineering/
    - title: Forum
      url: https://forum.nucleus.engineering/
    # - title: Help
    #   children:
    #   - title: Forum
    #     url: https://nucleus.discourse.group/
    #   - title: FAQs
    #     url: /docs/about/faqs
  options:
    logo: assets/logo-v1.png
    logo_url: https://bnext.bio/nucleus
    style: assets/style-sheet.css
    folders: true
    favicon: favicon.ico
    # favicon: https://raw.githubusercontent.com/jupyter-book/jupyter-book/refs/heads/next/docs/media/images/favicon.ico
    # logo_dark: https://raw.githubusercontent.com/jupyter-book/jupyter-book/refs/heads/next/docs/media/images/logo-dark.svg