version: 1
project:
  open_access: true
  license:
    content: CC-BY-4.0
    code: cern-ohl-p

site:
  template: book-theme
  nav: 
    - title: Docs
      # url: https://github.com/ProjectPythia/pythia-foundations/blob/main/myst.yml
      url: /docs/guides/getting-started
    - title: Developer Notes
      url: https://devnotes.bnext.bio/
    - title: Hub
      url: https://bnext.bio/hub
    - title: Ecosystem
      url: https://bnext.bio/nucleus
    - title: Help
      children:
      - title: Forum
        url: https://nucleus.discourse.group/
      - title: Zulip
        url: https://nucleus-engineering.zulipchat.com/#narrow/channel/525991-Zulip
  options:
    logo: /resources/logo-v1.png
    logo_url: https://bnext.bio/nucleus
    style: /resources/style-sheet.css
    folders: true
    # favicon: favicon.ico
    # favicon: https://raw.githubusercontent.com/jupyter-book/jupyter-book/refs/heads/next/docs/media/images/favicon.ico
    # logo_dark: https://raw.githubusercontent.com/jupyter-book/jupyter-book/refs/heads/next/docs/media/images/logo-dark.svg