#!/usr/bin/env python3
"""
build-materials-reference.py — aggregate one distribution-wide materials table.

Scans every BOM table across ``docs/`` (via bom_common.index_materials) and
emits a single deduplicated reference table — every material used anywhere in
the Distribution, with the processes that use it — as a gitignored generated
partial that ``guides/materials-reference.md`` includes. Like the lab-ready
PDFs (issue #10), the partial is DERIVED: never committed, rebuilt at deploy so
it cannot drift from the source pages.

It also prints a QA report to stdout of near-duplicates — the same chemical /
product name catalogued under more than one part # across pages — which are the
harmonization candidates worth reconciling.

Run before ``myst build`` (the deploy ordering), same as build-protocols.py.

Usage:
    python3 scripts/build-materials-reference.py
"""

import sys
from collections import defaultdict
from pathlib import Path

from bom_common import (  # noqa: E402  (sibling module, resolved via sys.path[0])
    index_materials,
    norm_name,
)

DOCS_ROOT = Path("docs")
OUT_PARTIAL = Path("guides/generated/materials-reference-table.md")

COLUMNS = ["Name", "Category", "Product", "Manufacturer",
           "Part #", "Price", "Storage", "Link", "Used in"]


def _cell(value: str) -> str:
    """Escape pipes so a value can't break the markdown table."""
    return (value or "").replace("|", "\\|").strip()


def build_table(index) -> str:
    rows = []
    for entry in index.values():
        link = entry.get("link", "")
        link_md = f"[link]({link})" if link else ""
        rows.append({
            "Name": entry.get("name", ""),
            "Category": entry.get("category", ""),
            "Product": entry.get("product", ""),
            "Manufacturer": entry.get("manufacturer", ""),
            "Part #": entry.get("part", ""),
            "Price": entry.get("price", ""),
            "Storage": entry.get("storage", ""),
            "Link": link_md,
            "Used in": ", ".join(sorted(entry.get("used_in", []))),
        })
    rows.sort(key=lambda r: (r["Category"].lower(), r["Name"].lower()))

    lines = [
        "<!-- GENERATED by scripts/build-materials-reference.py — do not edit;"
        " rebuilt at deploy. -->",
        "",
        ":::{table} Distribution-wide materials reference",
        ":label: tbl:materials-reference",
        "",
        "| " + " | ".join(COLUMNS) + " |",
        "| " + " | ".join(["---"] * len(COLUMNS)) + " |",
    ]
    for r in rows:
        lines.append("| " + " | ".join(_cell(r[c]) for c in COLUMNS) + " |")
    lines.append(":::")
    lines.append("")
    return "\n".join(lines)


def near_duplicate_report(index) -> list:
    """Group materials by normalized name; report names carried under more than
    one distinct (manufacturer, part #) key."""
    by_name = defaultdict(list)
    for key, entry in index.items():
        for nm in {norm_name(entry["name"]), norm_name(entry["product"])}:
            if nm:
                by_name[nm].append((key, entry))
                break  # index once per entry, by its primary name
    report = []
    for nm, items in sorted(by_name.items()):
        keys = {k for k, _ in items}
        if len(keys) > 1:
            report.append((nm, items))
    return report


def main() -> int:
    if not DOCS_ROOT.exists():
        print(f"ERROR: '{DOCS_ROOT}' not found — run from the repo root.")
        return 1

    index, conflicts = index_materials(DOCS_ROOT)

    OUT_PARTIAL.parent.mkdir(parents=True, exist_ok=True)
    OUT_PARTIAL.write_text(build_table(index), encoding="utf-8")
    print(f"✓ Wrote {OUT_PARTIAL} ({len(index)} materials).")

    dups = near_duplicate_report(index)
    if dups:
        print(f"\n⚠️  Near-duplicate QA report ({len(dups)} name(s) under "
              f"multiple part #s — harmonization candidates):")
        for nm, items in dups:
            print(f"  • {nm}:")
            for (man, part), entry in items:
                print(f"      - {entry['manufacturer']} {entry['part']} "
                      f"(used in {', '.join(entry['used_in'])})")

    if conflicts:
        print(f"\nℹ️  {len(conflicts)} field conflict(s) on shared "
              f"(manufacturer, part #) keys (first non-empty value kept):")
        for c in conflicts[:20]:
            print(f"  - {c['key']} {c['field']}: kept {c['kept']!r} "
                  f"(saw {c['other']!r} in {c['slug']})")
        if len(conflicts) > 20:
            print(f"  ...and {len(conflicts) - 20} more")

    return 0


if __name__ == "__main__":
    sys.exit(main())
